---
- hosts: us-east-2
  remote_user: ubuntu

  vars:
    env:
      DATABASE_NAME: 'imagersite_db'
      USER_NAME: 'imagersite'
      DB_PASSWORD: 'W0rdpa88'
      HOST: 'example-db.cdmqe2srdqbh.us-east-2.rds.amazonaws.com'
      SECRET_KEY: '2t#jmg22gz)dxy%u%7zk=2sb-94kr8znov(8t)a!$bsrnlt^_6'
      EMAIL_PASSWORD: 'learnmorefaster'
      DEBUG: 'False'
      ALLOWED_HOSTS: 'ec2-52-14-94-237.us-east-2.compute.amazonaws.com'

  tasks:
    - name: Update the Ubuntu machine with all the latest stuff
      apt: update_cache=yes
      become: yes
      become_method: sudo

    - name: Upgrade the Ubuntu machine with all the latest stuff
      apt: upgrade=yes
      become: yes
      become_method: sudo

    - name: Install Basic Unix-level Services
      apt: name={{ item }} state=latest
      become: yes
      become_method: sudo
      with_items:
        - nginx
        - python3
        - python3-pip
        - python3.4-venv
        - git
        - gunicorn
        - libtiff5-dev
        - libjpeg8-dev
        - zlib1g-dev
        - libfreetype6-dev
        - liblcms2-dev
        - libwebp-dev
        - tcl8.6-dev
        - tk8.6-dev
        - python-tk
        - python-dev
        - libpq-dev

    - name: Clone the Imager App to the Home Directory
      git: clone=yes repo=https://github.com/clair3st/django-imager.git dest=/home/ubuntu/django-imager version=deployment

    - name: Manually create the initial virtualenv
      command: virtualenv /home/ubuntu/ENV -p python3.4 creates="/home/ubuntu/ENV"

    - name: Install the packages specified in requirements.pip in the Python 3 environment
      become: yes
      become_method: sudo
      pip: 
        requirements: /home/ubuntu/django-imager/requirements.pip
        virtualenv: /home/ubuntu/ENV
        # virtualenv_python: python3.4

    - name: Install gunicorn to the virtualenv
      become: yes
      become_method: sudo
      pip: virtualenv=/home/ubuntu/ENV name=gunicorn

    - name: Migrate Django models to database
      django_manage:
        command: migrate
        app_path: /home/ubuntu/django-imager/imagersite/
        virtualenv: /home/ubuntu/ENV/
      environment: "{{env}}"

    - name: Change permissions on media folder
      become: yes
      become_method: sudo
      file: 
        path: /home/ubuntu/django-imager/imagersite/media
        state: touch
        mode: 0777
        
    - name: Register the old default file
      stat: path=/etc/nginx/sites-available/default.old
      register: default_stat

    - name: Rename old default file
      command: mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.old
      when: not default_stat.stat.exists
      become: yes
      become_method: sudo

    - name: Create a new default file for nginx
      template: src=simple_nginx_config dest=/etc/nginx/sites-available/default
      become: yes
      become_method: sudo

    - name: Restart nginx service
      service: name=nginx state=restarted
      become: yes
      become_method: sudo

    - name: Copy upstart script into /etc/init/
      template: src=imagersite.conf dest=/etc/init/imagersite.conf
      become: yes
      become_method: sudo

    - name: Restart the imager upstart job
      service: name=imagersite state=restarted
      become: yes
      become_method: sudo