---
- hosts: us-east-2
  remote_user: ubuntu

  vars:
    vars_files:
    - vars.yml
    env:
      DATABASE_NAME: {{db_name}}
      USER_NAME: {{db_user}}
      DB_PASSWORD: {{db_password}}
      HOST: {{db_host}}
      SECRET_KEY: {{secret_key}}
      EMAIL_PASSWORD: {{email_password}}
      ALLOWED_HOSTS: {{allowed_host}}
  tasks:
    - name: Update the Ubuntu machine with all the latest stuff
      apt: update_cache=yes
      become: yes
      become_method: sudo

    - name: Upgrade the Ubuntu machine with all the latest stuff
      apt: upgrade=yes
      become: yes
      become_method: sudo

    - name: Install Basic Unix-level Services
      apt: name={{ item }} state=latest
      become: yes
      become_method: sudo
      with_items:
        - nginx
        - python3
        - python3-pip
        - python3.4-venv
        - git
        - gunicorn
        - libtiff5-dev
        - libjpeg8-dev
        - zlib1g-dev
        - libfreetype6-dev
        - liblcms2-dev
        - libwebp-dev
        - tcl8.6-dev
        - tk8.6-dev
        - python-tk
        - python-dev
        - libpq-dev

    - name: Clone the Imager App to the Home Directory
      git: clone=yes repo={{project_repo}} dest={{install_root}} version={{branch}}

    - name: Manually create the initial virtualenv
      command: virtualenv {{env_path}} -p python3.4 creates="{{env_path}}"

    - name: Install the packages specified in requirements.pip in the Python 3 environment
      become: yes
      become_method: sudo
      pip: 
        requirements: "{{install_root}}"/requirements.pip
        virtualenv: "{{env_path}}"
        # virtualenv_python: python3.4

    - name: Install gunicorn to the virtualenv
      become: yes
      become_method: sudo
      pip: virtualenv={{env_path}} name=gunicorn

    - name: Migrate Django models to database
      django_manage:
        command: migrate
        app_path: "{{ install_root }}"/"{{ project_name }}"
        virtualenv: "{{env_path}}"
      environment: "{{env}}"

    - name: Change permissions on media folder
      become: yes
      become_method: sudo
      file: 
        path: "{{media_root}}"
        state: touch
        mode: 0777
        
    - name: Register the old default file
      stat: path=/etc/nginx/sites-available/default.old
      register: default_stat

    - name: Rename old default file
      command: mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.old
      when: not default_stat.stat.exists
      become: yes
      become_method: sudo

    - name: Create a new default file for nginx
      template: src=simple_nginx_config.j2 dest=/etc/nginx/sites-available/default
      become: yes
      become_method: sudo

    - name: Restart nginx service
      service: name=nginx state=restarted
      become: yes
      become_method: sudo

    - name: Copy upstart script into /etc/init/
      template: src={{project_name}}.j2 dest=/etc/init/{{project_name}}.j2
      become: yes
      become_method: sudo

    - name: Restart the imager upstart job
      service: name={{project_name}} state=restarted
      become: yes
      become_method: sudo